#FIXME: make the env loading from the .env file
#FIXME: mount the drive to datbase (2 diffrent places 1 for backup)

services:
  koala-postgres:
    image: postgres:16
    container_name: koala-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - koalaNETWORK

  koala-backend:
    build:
      context: ./backend/koala
      dockerfile: Dockerfile
    container_name: koala-backend
    depends_on:
      - koala-postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_HOST: koala-postgres
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - koalaNETWORK

networks:
  koalaNETWORK: