services:
  koala-postgres:
    image: postgres:16
    container_name: koala-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - koalaNETWORK
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10

  koala-backend:
    build:
      context: ./backend/koala
      dockerfile: Dockerfile
    container_name: koala-backend
    depends_on:
      koala-postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - koalaNETWORK

networks:
  koalaNETWORK: