services:
  koala-postgres:
    image: postgres:16
    container_name: koala-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - koalaNETWORK
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  koala-backend:
    build:
      context: ./backend/koala
      dockerfile: Dockerfile
    container_name: koala-backend
    depends_on:
      koala-postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PUBLIC_STORAGE_PATH: ${CONTAINER_PUBLIC_DATA_PATH}
      PRIVATE_STORAGE_PATH: ${CONTAINER_PRIVATE_DATA_PATH}
    volumes:
      - ${BACKEND_PUBLIC_DATA_PATH}:${CONTAINER_PUBLIC_DATA_PATH}
      - ${BACKEND_PRIVATE_DATA_PATH}:${CONTAINER_PRIVATE_DATA_PATH}
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - koalaNETWORK

networks:
  koalaNETWORK: