// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using koala.src.Modules.Account.Data;

#nullable disable

namespace koala.src.Modules.Account.Data.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    [Migration("20260917052716_InitialAccountMigration")]
    partial class InitialAccountMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("account")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("koala.src.Modules.Account.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("links", "account");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", "account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a027c5-d599-73de-bd5c-11f84a3fc125"),
                            Name = "ORGANIZATION_ADMIN"
                        },
                        new
                        {
                            Id = new Guid("01a027c5-d599-73de-bd5c-14db087cc58f"),
                            Name = "ORGANIZATION_EDITOR"
                        },
                        new
                        {
                            Id = new Guid("01a027c5-d599-73de-bd5c-18c05fc3fa53"),
                            Name = "ORGANIZATION_REVIUER"
                        },
                        new
                        {
                            Id = new Guid("01a027c5-d599-73de-bd5c-1f8e68687e51"),
                            Name = "TEAM_ADMIN"
                        },
                        new
                        {
                            Id = new Guid("01a027c5-d599-73de-bd5c-2068e28b6cf3"),
                            Name = "TEAM_PLAYER"
                        });
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("sessions", "account");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("NameAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("name_accepted");

                    b.HasKey("Id");

                    b.ToTable("teams", "account");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.TeamJoinCode", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("join_code");

                    b.HasKey("TeamId");

                    b.ToTable("TeamJoinCodes", "account");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("team_members", "account");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AcceptedRodo")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted_rodo");

                    b.Property<bool>("AcceptedRules")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted_rules");

                    b.Property<bool>("Censored")
                        .HasColumnType("boolean")
                        .HasColumnName("censored");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("NameFirst")
                        .HasColumnType("text")
                        .HasColumnName("name_first");

                    b.Property<string>("NameLast")
                        .HasColumnType("text")
                        .HasColumnName("name_last");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.ToTable("users", "account");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "account");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.Link", b =>
                {
                    b.HasOne("koala.src.Modules.Account.Entities.User", "User")
                        .WithMany("Links")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.Session", b =>
                {
                    b.HasOne("koala.src.Modules.Account.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.TeamJoinCode", b =>
                {
                    b.HasOne("koala.src.Modules.Account.Entities.Team", "Team")
                        .WithOne("TeamJoinCode")
                        .HasForeignKey("koala.src.Modules.Account.Entities.TeamJoinCode", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.TeamMember", b =>
                {
                    b.HasOne("koala.src.Modules.Account.Entities.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("koala.src.Modules.Account.Entities.User", "User")
                        .WithMany("TeamMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.UserRole", b =>
                {
                    b.HasOne("koala.src.Modules.Account.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("koala.src.Modules.Account.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.Team", b =>
                {
                    b.Navigation("TeamJoinCode")
                        .IsRequired();

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("koala.src.Modules.Account.Entities.User", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Sessions");

                    b.Navigation("TeamMembers");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
