// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using koala.src.Modules.Cms.Data;

#nullable disable

namespace koala.src.Modules.Cms.Data.Migrations
{
    [DbContext(typeof(CmsDbContext))]
    [Migration("20260925164700_SomePendingChange")]
    partial class SomePendingChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cms")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("koala.src.Modules.Cms.Entities.Koalicjant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsVisiable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visiable");

                    b.Property<string>("NameFirst")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_first");

                    b.Property<string>("NameLast")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_last");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("koalicjants", "cms");
                });

            modelBuilder.Entity("koala.src.Modules.Cms.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<bool>("IsVisable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("posts", "cms");
                });

            modelBuilder.Entity("koala.src.Modules.Cms.Entities.PublicFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("public_files", "cms");
                });

            modelBuilder.Entity("koala.src.Modules.Cms.Entities.Sponsor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVisiable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visiable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("sponsors", "cms");
                });

            modelBuilder.Entity("koala.src.Modules.Cms.Entities.StaticPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("static_pages", "cms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a065c3-3bec-7224-b7b2-abc51fe1d87f"),
                            ContentJson = "{}",
                            Name = "HOME_PAGE",
                            UpdatedAt = new DateTime(2026, 7, 6, 7, 6, 7, 0, DateTimeKind.Utc),
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("01a065c3-3bec-7224-b7b2-afa2801aa4a4"),
                            ContentJson = "{}",
                            Name = "TASKS_PAGE",
                            UpdatedAt = new DateTime(2026, 7, 6, 7, 6, 7, 0, DateTimeKind.Utc),
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("01a065c3-3bec-7224-b7b2-b241dc642361"),
                            ContentJson = "{}",
                            Name = "HISTORY_PAGE",
                            UpdatedAt = new DateTime(2026, 7, 6, 7, 6, 7, 0, DateTimeKind.Utc),
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("01a065c3-3bec-7224-b7b2-b426015c004a"),
                            ContentJson = "{}",
                            Name = "RULES_PAGE",
                            UpdatedAt = new DateTime(2026, 7, 6, 7, 6, 7, 0, DateTimeKind.Utc),
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("01a065c3-3bec-7224-b7b2-b86c61973289"),
                            ContentJson = "{}",
                            Name = "KOALICJANTS_PAGE",
                            UpdatedAt = new DateTime(2026, 7, 6, 7, 6, 7, 0, DateTimeKind.Utc),
                            Version = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
